pub enum Token<'source> {
    Nil,
    OpenParen,
    CloseParen,
    OpenHashBrace,
    OpenBrace,
    CloseBrace,
    OpenBracket,
    CloseBracket,
    Boolean(bool),
    String(&'source str),
    Character(char),
    Symbol(&'source str),
    Keyword(&'source str),
    Tag(&'source str),
    Discard(&'source str),
    Integer(i64),
    Float(f64),
}